In [5]:
import pandas as pd

In [6]:
games = pd.read_csv(r"D:\DEV\PROJECT\video game sales and engagement analysis\games.csv")
sales = pd.read_csv(r"D:\DEV\PROJECT\video game sales and engagement analysis\vgsales.csv")

In [7]:
games.head()

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
1,1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K
3,3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,4.9K,1.8K
4,4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,8.3K,2.3K

In [8]:
games.isnull().sum()

Unnamed: 0            0
Title                 0
Release Date          0
Team                  1
Rating               13
Times Listed          0
Number of Reviews     0
Genres                0
Summary               1
Reviews               0
Plays                 0
Playing               0
Backlogs              0
Wishlist              0
dtype: int64

In [9]:
sales.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [16]:
sales.isnull().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
clean_name        0
dtype: int64

In [10]:
def clean_title(title):
    if pd.isnull(title):
        return ''
    return str(title).strip().lower().replace(":", "").replace("-", "").replace(",", " ").replace(".", "")

games['clean_title'] = games['Title'].apply(clean_title)
sales['clean_name'] = sales['Name'].apply(clean_title)

merged = pd.merge(games, sales, how= 'left', left_on='clean_title', right_on='clean_name')

merged.drop(columns=['clean_title', 'clean_name'], inplace=True)

merged.to_csv("merged_games.csv", index=False)

print("MERGING COMPLETED. final shape:", merged.shape)

MERGING COMPLETED. final shape: (2269, 25)

In [11]:
merge = pd.read_csv("merged_games.csv")

In [12]:
merge.head()

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,...,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
merge.isnull().sum()

Unnamed: 0             0
Title                  0
Release Date           0
Team                   1
Rating                13
Times Listed           0
Number of Reviews      0
Genres                 0
Summary                1
Reviews                0
Plays                  0
Playing                0
Backlogs               0
Wishlist               0
Rank                 846
Name                 846
Platform             846
Year                 861
Genre                846
Publisher            849
NA_Sales             846
EU_Sales             846
JP_Sales             846
Other_Sales          846
Global_Sales         846
dtype: int64

In [13]:
import mysql.connector

In [38]:
import mysql.connector
conn = mysql.connector.connect(
    host = "localhost",
    user = "root",
    password = "Dev@0210"
)
cursor = conn.cursor()

In [39]:
cursor.execute("CREATE DATABASE IF NOT EXISTS game_salesdata_db")
print("Mysql Database game_saledata_db created!")

Mysql Database game_saledata_db created!

In [40]:
cursor.execute("USE game_salesdata_db")
cursor.execute("""
CREATE TABLE IF NOT EXISTS games_data (
    unnamed INT,
    title VARCHAR(255),
    release_date VARCHAR(20),
    team VARCHAR(100),
    rating VARCHAR(10),
    times_listed VARCHAR(50),
    number_of_reviews VARCHAR(50),
    genres VARCHAR(255),
    summary TEXT,
    reviews TEXT,
    plays VARCHAR(50),
    playing INT,
    backlogs INT,
    wishlist INT
)
""")
conn.commit()
print("table created successfully.")

table created successfully.

In [48]:
# select only the columns that match the games_data table (drop the extra `clean_title` column)
cols = [
    'Unnamed: 0', 'Title', 'Release Date', 'Team', 'Rating',
    'Times Listed', 'Number of Reviews', 'Genres', 'Summary',
    'Reviews', 'Plays', 'Playing', 'Backlogs', 'Wishlist'
]

query = """
    INSERT INTO games_data (unnamed, title, release_date, team, rating, times_listed, number_of_reviews, genres, summary, reviews, plays, playing, backlogs, wishlist)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

def parse_count(x):
    """Parse strings like '3.8K', '2M', '230' into integers (or None)."""
    if pd.isnull(x):
        return None
    s = str(x).strip().lower().replace(',', '')
    try:
        if s.endswith('k'):
            return int(float(s[:-1]) * 1000)
        if s.endswith('m'):
            return int(float(s[:-1]) * 1_000_000)
        return int(float(s))
    except Exception:
        return None

# work on a copy to avoid modifying original dataframe
df_trim = games[cols].copy()

# convert the integer columns to actual ints (these were defined as INT in MySQL)
for c in ['Playing', 'Backlogs', 'Wishlist']:
    if c in df_trim.columns:
        df_trim[c] = df_trim[c].apply(parse_count)

# replace NaN with None so MySQL receives NULL for missing values
data_list_trimmed = df_trim.where(pd.notnull(df_trim), None).values.tolist()

cursor.executemany(query, data_list_trimmed)
conn.commit()
print("data inserted using to_list")

data inserted using to_list

In [44]:
del(data_list)

In [24]:
cursor.execute("USE game_salesdata_db")
cursor.execute("""
CREATE TABLE IF NOT EXISTS sales_data (
    `Rank` INT,
    `Name` VARCHAR(255),
    `Platform` VARCHAR(10),
    `Year` INT,
    `Genre` VARCHAR(50),
    `Publisher` VARCHAR(100),
    `NA_Sales` FLOAT,
    `EU_Sales` FLOAT,
    `JP_Sales` FLOAT,
    `Other_Sales` FLOAT,
    `Global_Sales` FLOAT
)
""")
conn.commit()
print("table created successfully.")

table created successfully.

In [50]:
# select only the columns that match the sales_data table (exclude the extra `clean_name` column)
cols = ['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']

# work on a copy so we don't overwrite the original dataframe
df_sales_trim = sales[cols].copy()

# ensure Year is an int or None (MySQL INT)
df_sales_trim['Year'] = df_sales_trim['Year'].apply(lambda x: int(x) if pd.notnull(x) else None)

# replace NaN with None so MySQL receives NULL for missing values
data_list = df_sales_trim.where(pd.notnull(df_sales_trim), None).values.tolist()

query = """
    INSERT INTO sales_data (`Rank`, `Name`, `Platform`, `Year`, `Genre`, `Publisher`, `NA_Sales`, `EU_Sales`, `JP_Sales`, `Other_Sales`, `Global_Sales`)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""
cursor.executemany(query, data_list)
conn.commit()
print("data inserted using to_list")

data inserted using to_list

In [52]:
cursor.execute("USE game_salesdata_db")
cursor.execute("""
CREATE TABLE IF NOT EXISTS merge_data (
    unnamed INT,
    title VARCHAR(255),
    release_date VARCHAR(20),
    team VARCHAR(255),
    rating FLOAT,
    times_listed VARCHAR(50),
    number_of_reviews VARCHAR(50),
    genres VARCHAR(255),
    summary TEXT,
    reviews TEXT,
    plays VARCHAR(50),
    playing INT,
    backlogs INT,
    wishlist INT,
    `rank` INT,
    name VARCHAR(255),
    platform VARCHAR(50),
    year INT,
    genre VARCHAR(50),
    publisher VARCHAR(100),
    NA_Sales FLOAT,
    EU_Sales FLOAT,
    JP_Sales FLOAT,
    Other_Sales FLOAT,
    Global_Sales FLOAT
)
""")
conn.commit()
print("table created successfully.")

table created successfully.

In [55]:
# Select columns in the order matching the SQL INSERT statement
cols_ordered = [
    'Unnamed: 0', 'Title', 'Release Date', 'Team', 'Rating',
    'Times Listed', 'Number of Reviews', 'Genres', 'Summary',
    'Reviews', 'Plays', 'Playing', 'Backlogs', 'Wishlist',
    'Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher',
    'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'
]

df_merge_trim = merge[cols_ordered].copy()

# convert Playing/Backlogs/Wishlist from strings like '3.8K' to ints (uses parse_count defined earlier)
for c in ['Playing', 'Backlogs', 'Wishlist']:
    if c in df_merge_trim.columns:
        df_merge_trim[c] = df_merge_trim[c].apply(parse_count)

# convert Rank and Year to ints (or None) to match SQL INT columns
for c in ['Rank', 'Year']:
    if c in df_merge_trim.columns:
        df_merge_trim[c] = df_merge_trim[c].apply(lambda x: int(x) if pd.notnull(x) else None)

# replace NaN with None so MySQL receives NULL for missing values
data_list = df_merge_trim.where(pd.notnull(df_merge_trim), None).values.tolist()

query = """
    INSERT INTO merge_data (unnamed, title, release_date, team, rating, times_listed, number_of_reviews, genres, summary, reviews, plays, playing, backlogs, wishlist, `rank`, name, platform, year, genre, publisher, NA_Sales, EU_Sales, JP_Sales, Other_Sales, Global_Sales)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""
cursor.executemany(query, data_list)
conn.commit()
print("data inserted using to_list")

data inserted using to_list